### ISSUE TITLE
"induction matrix dimension and word embedding dimension must be the same"

### ISSUE THREAD

**Issue by fsonntag** [NLPrinceton/ALaCarte#1]
Hey,
thanks for this interesting repository! 
I'm trying to experiment with the code by inducing vectors for certain words, nevertheless I run into the issue of `"induction matrix dimension and word embedding dimension must be the same"`.
when invoking `python alacarte.py testdump --source ...glove.6B/glove.6B.300d.txt --targets words.txt --corpus corpus.txt --matrix transform/6B.300d.bin`, I get this issue. 
The dimension of the embeddings seems fine, but the value `d` of the transformation file is 282. A similar problem appears with the files in other dimensions.

So am I using the script wrong? Or is there a problem with the transformation files?

**Comment by mkhodak** [comment]
Hi, thanks for raising this issue. It looks like all the transforms were saved as doubles (np.float64) and not floats (np.float32). Still figuring out why this happened, but in the meantime have updated the transform files.

**Comment by fsonntag** [comment]
Great, thanks a lot!
