### ISSUE TITLE
Contextualized Rare Words details

### ISSUE THREAD

**Issue by rajicon** [NLPrinceton/ALaCarte#3]
I'm interested in experimenting using the CRW dataset, and so I was wondering if I could get more details on how the word2vec model was trained.  Was gensim used?  Was it a skipgram or cbow model?  What was the sampling?  Epochs?  Etc?  I want to compare my own model, and would be interested in these details or if possible, the training code itself.

**Comment by nsaunshi** [comment]
This [github repository](https://github.com/tmikolov/word2vec) was used to build the word2vec binary. The following command was used to train the embeddings.

`./word2vec -train WWC.txt -output vectors.txt -size 300 -sample 1e-4 -save-vocab WWC_vocab.txt -cbow 0 -min-count 100 -threads 32`

The other options were set to the default values. Specifically, the skipgram model was used with 5 negative samples, window size of 5 and was run for 5 iterations.
